// Hand-curated content for the Atlas game: what gets asked, what it is called
// in English and Romanian, and how hard it is.
//
// Tiers: 1 = everybody knows it ... 5 = obscure or properly weird.
// Tier 0 = drawn and named (so it can be a wrong answer or tell you what you
// tapped), but never asked about.

// ------------------------------------------------------------- countries

// Map-finding order starts here: big, famous, or home.
export const MAP_TIER1 = [
  'RO', 'RU', 'US', 'CA', 'BR', 'AU', 'CN', 'IN', 'FR', 'IT', 'ES', 'GB',
  'DE', 'JP', 'MX', 'AR', 'EG', 'UA', 'TR', 'MD', 'GL', 'ZA', 'GR', 'NO',
]

// Territories and unrecognised states: [en, ro, fame 0..1].
export const TERRITORIES = {
  GL: ['Greenland', 'Groenlanda', 0.9],
  PR: ['Puerto Rico', 'Puerto Rico', 0.45],
  HK: ['Hong Kong', 'Hong Kong', 0.5],
  MO: ['Macau', 'Macao', 0.2],
  FO: ['Faroe Islands', 'Insulele Feroe', 0.3],
  NC: ['New Caledonia', 'Noua Caledonie', 0.25],
  PF: ['French Polynesia', 'Polinezia Franceză', 0.3],
  GF: ['French Guiana', 'Guyana Franceză', 0.35],
  RE: ['Réunion', 'Réunion', 0.2],
  GP: ['Guadeloupe', 'Guadelupa', 0.15],
  MQ: ['Martinique', 'Martinica', 0.15],
  YT: ['Mayotte', 'Mayotte', 0.05],
  SJ: ['Svalbard', 'Svalbard', 0.4],
  BV: ['Bouvet Island', 'Insula Bouvet', 0.02],
  GI: ['Gibraltar', 'Gibraltar', 0.4],
  AX: ['Åland Islands', 'Insulele Åland', 0.1],
  IM: ['Isle of Man', 'Insula Man', 0.2],
  JE: ['Jersey', 'Jersey', 0.15],
  GG: ['Guernsey', 'Guernsey', 0.1],
  BM: ['Bermuda', 'Bermude', 0.35],
  KY: ['Cayman Islands', 'Insulele Cayman', 0.15],
  TC: ['Turks & Caicos', 'Turks și Caicos', 0.05],
  VG: ['British Virgin Is.', 'Ins. Virgine Britanice', 0.05],
  VI: ['US Virgin Islands', 'Ins. Virgine Americane', 0.05],
  AW: ['Aruba', 'Aruba', 0.1],
  CW: ['Curaçao', 'Curaçao', 0.1],
  SX: ['Sint Maarten', 'Sint Maarten', 0.03],
  BQ: ['Caribbean Netherlands', 'Caraibii Olandeze', 0.02],
  MF: ['Saint Martin', 'Saint-Martin', 0.03],
  BL: ['Saint Barthélemy', 'Saint-Barthélemy', 0.03],
  PM: ['St. Pierre & Miquelon', 'Saint-Pierre și Miquelon', 0.03],
  WF: ['Wallis & Futuna', 'Wallis și Futuna', 0.02],
  TF: ['French Southern Lands', 'Teritoriile Australe Franceze', 0.03],
  HM: ['Heard Island', 'Insula Heard', 0.02],
  NF: ['Norfolk Island', 'Insula Norfolk', 0.03],
  CX: ['Christmas Island', 'Insula Christmas', 0.05],
  CC: ['Cocos Islands', 'Insulele Cocos', 0.03],
  GS: ['South Georgia', 'Georgia de Sud', 0.05],
  IO: ['Chagos Islands', 'Insulele Chagos', 0.03],
  SH: ['Saint Helena', 'Sfânta Elena', 0.1],
  PN: ['Pitcairn Islands', 'Insulele Pitcairn', 0.05],
  AI: ['Anguilla', 'Anguilla', 0.03],
  MS: ['Montserrat', 'Montserrat', 0.03],
  FK: ['Falkland Islands', 'Insulele Falkland', 0.35],
  CK: ['Cook Islands', 'Insulele Cook', 0.05],
  NU: ['Niue', 'Niue', 0.02],
  TK: ['Tokelau', 'Tokelau', 0.02],
  AS: ['American Samoa', 'Samoa Americană', 0.05],
  GU: ['Guam', 'Guam', 0.15],
  MP: ['Northern Mariana Is.', 'Insulele Mariane de Nord', 0.03],
  EH: ['Western Sahara', 'Sahara Occidentală', 0.35],
  SOL: ['Somaliland', 'Somaliland', 0.15],
  CYN: ['Northern Cyprus', 'Ciprul de Nord', 0.2],
}

// Map units folded into the country around them for the country game, so
// tapping Guantánamo still counts as Cuba.
export const HOST = {
  'US Naval Base Guantanamo Bay': 'CU',
  'Baykonur Cosmodrome': 'KZ',
  'Akrotiri Sovereign Base Area': 'CY',
  'Dhekelia Sovereign Base Area': 'CY',
  'Cyprus No Mans Area': 'CY',
  'Brazilian Island': 'BR',
}

// Drawn as land, never asked: disputed specks, Antarctica and similar.
export const NOT_PLAYABLE = new Set([
  'Antarctica', 'Siachen Glacier', 'Bir Tawil', 'Southern Patagonian Ice Field',
  'Spratly Islands', 'Paracel Islands', 'Scarborough Reef', 'Serranilla Bank',
  'Bajo Nuevo Bank (Petrel Is.)', 'Clipperton Island', 'Coral Sea Islands',
  'Johnston Atoll', 'Jarvis Island', 'Baker Island', 'Howland Island',
  'Wake Atoll', 'Midway Islands', 'Navassa Island', 'Palmyra Atoll', 'Kingman Reef',
])

// --------------------------------------------------------------- regions
//
// A scene is one country (or a single odd place) drawn with its internal
// borders. `src: 'admin1'` reads Natural Earth states/provinces, `src: 'units'`
// reads admin-0 map units (UK nations, Belgian regions, ...). `group` maps a
// source feature to the unit it belongs to - several features can dissolve
// into one unit (French departments into regions). Units missing from `units`
// are still drawn, unnamed.

export const SCENES = [
  {
    id: 'US', src: 'admin1', iso: 'US', drop: ['District of Columbia'],
    units: {
      'Alaska': ['Alaska', 'Alaska', 1], 'Texas': ['Texas', 'Texas', 1],
      'California': ['California', 'California', 1], 'Florida': ['Florida', 'Florida', 1],
      'Hawaii': ['Hawaii', 'Hawaii', 1], 'New York': ['New York', 'New York', 2],
      'Nevada': ['Nevada', 'Nevada', 2], 'Arizona': ['Arizona', 'Arizona', 2],
      'Washington': ['Washington', 'Washington', 3], 'Louisiana': ['Louisiana', 'Louisiana', 3],
      'Colorado': ['Colorado', 'Colorado', 3], 'Utah': ['Utah', 'Utah', 3],
      'Michigan': ['Michigan', 'Michigan', 3], 'Maine': ['Maine', 'Maine', 4],
      'Montana': ['Montana', 'Montana', 4], 'Oregon': ['Oregon', 'Oregon', 4],
      'New Mexico': ['New Mexico', 'New Mexico', 4], 'Oklahoma': ['Oklahoma', 'Oklahoma', 4],
      'Wyoming': ['Wyoming', 'Wyoming', 4], 'Idaho': ['Idaho', 'Idaho', 5],
      'North Dakota': ['North Dakota', 'Dakota de Nord', 5], 'Rhode Island': ['Rhode Island', 'Rhode Island', 5],
      'South Dakota': ['South Dakota', 'Dakota de Sud', 0], 'Nebraska': ['Nebraska', 'Nebraska', 0],
      'Kansas': ['Kansas', 'Kansas', 0], 'Minnesota': ['Minnesota', 'Minnesota', 0],
      'Iowa': ['Iowa', 'Iowa', 0], 'Missouri': ['Missouri', 'Missouri', 0],
      'Arkansas': ['Arkansas', 'Arkansas', 0], 'Mississippi': ['Mississippi', 'Mississippi', 0],
      'Alabama': ['Alabama', 'Alabama', 0], 'Georgia': ['Georgia (USA)', 'Georgia (SUA)', 0],
      'Tennessee': ['Tennessee', 'Tennessee', 0], 'Kentucky': ['Kentucky', 'Kentucky', 0],
      'Illinois': ['Illinois', 'Illinois', 0], 'Wisconsin': ['Wisconsin', 'Wisconsin', 0],
      'Indiana': ['Indiana', 'Indiana', 0], 'Ohio': ['Ohio', 'Ohio', 0],
      'Pennsylvania': ['Pennsylvania', 'Pennsylvania', 0], 'West Virginia': ['West Virginia', 'Virginia de Vest', 0],
      'Virginia': ['Virginia', 'Virginia', 0], 'North Carolina': ['North Carolina', 'Carolina de Nord', 0],
      'South Carolina': ['South Carolina', 'Carolina de Sud', 0], 'Maryland': ['Maryland', 'Maryland', 0],
      'Delaware': ['Delaware', 'Delaware', 0], 'New Jersey': ['New Jersey', 'New Jersey', 0],
      'Connecticut': ['Connecticut', 'Connecticut', 0], 'Massachusetts': ['Massachusetts', 'Massachusetts', 0],
      'Vermont': ['Vermont', 'Vermont', 0], 'New Hampshire': ['New Hampshire', 'New Hampshire', 0],
    },
  },
  {
    id: 'CA', src: 'admin1', iso: 'CA',
    units: {
      'Nunavut': ['Nunavut', 'Nunavut', 2], 'Yukon': ['Yukon', 'Yukon', 2],
      'British Columbia': ['British Columbia', 'Columbia Britanică', 2], 'Ontario': ['Ontario', 'Ontario', 2],
      'Québec': ['Quebec', 'Québec', 2], 'Alberta': ['Alberta', 'Alberta', 3],
      'Northwest Territories': ['Northwest Territories', 'Teritoriile de Nord-Vest', 3],
      'Newfoundland and Labrador': ['Newfoundland & Labrador', 'Terra Nova și Labrador', 3],
      'Nova Scotia': ['Nova Scotia', 'Noua Scoție', 4], 'Saskatchewan': ['Saskatchewan', 'Saskatchewan', 4],
      'Manitoba': ['Manitoba', 'Manitoba', 4], 'Prince Edward Island': ['Prince Edward Island', 'Insula Prințului Eduard', 5],
      'New Brunswick': ['New Brunswick', 'New Brunswick', 5],
    },
  },
  {
    id: 'MX', src: 'admin1', iso: 'MX',
    units: {
      'Baja California': ['Baja California', 'Baja California', 2], 'Yucatán': ['Yucatán', 'Yucatán', 3],
      'Baja California Sur': ['Baja California Sur', 'Baja California Sur', 4], 'Chihuahua': ['Chihuahua', 'Chihuahua', 4],
      'Chiapas': ['Chiapas', 'Chiapas', 4], 'Quintana Roo': ['Quintana Roo', 'Quintana Roo', 4],
      'Sonora': ['Sonora', 'Sonora', 5], 'Oaxaca': ['Oaxaca', 'Oaxaca', 5], 'Jalisco': ['Jalisco', 'Jalisco', 5],
      'Distrito Federal': ['Mexico City', 'Ciudad de México', 0], 'Coahuila': ['Coahuila', 'Coahuila', 0],
      'Durango': ['Durango', 'Durango', 0], 'Sinaloa': ['Sinaloa', 'Sinaloa', 0], 'Nuevo León': ['Nuevo León', 'Nuevo León', 0],
      'Tamaulipas': ['Tamaulipas', 'Tamaulipas', 0], 'Veracruz': ['Veracruz', 'Veracruz', 0],
      'Guerrero': ['Guerrero', 'Guerrero', 0], 'Campeche': ['Campeche', 'Campeche', 0], 'Tabasco': ['Tabasco', 'Tabasco', 0],
    },
  },
  {
    id: 'BR', src: 'admin1', iso: 'BR',
    units: {
      'Amazonas': ['Amazonas', 'Amazonas', 2], 'Rio de Janeiro': ['Rio de Janeiro', 'Rio de Janeiro', 2],
      'São Paulo': ['São Paulo', 'São Paulo', 3], 'Bahia': ['Bahia', 'Bahia', 3],
      'Mato Grosso': ['Mato Grosso', 'Mato Grosso', 4], 'Pará': ['Pará', 'Pará', 4],
      'Rio Grande do Sul': ['Rio Grande do Sul', 'Rio Grande do Sul', 4], 'Minas Gerais': ['Minas Gerais', 'Minas Gerais', 5],
      'Acre': ['Acre', 'Acre', 5], 'Roraima': ['Roraima', 'Roraima', 5],
      'Mato Grosso do Sul': ['Mato Grosso do Sul', 'Mato Grosso do Sul', 0], 'Goiás': ['Goiás', 'Goiás', 0],
      'Tocantins': ['Tocantins', 'Tocantins', 0], 'Maranhão': ['Maranhão', 'Maranhão', 0], 'Piauí': ['Piauí', 'Piauí', 0],
      'Ceará': ['Ceará', 'Ceará', 0], 'Paraná': ['Paraná', 'Paraná', 0], 'Santa Catarina': ['Santa Catarina', 'Santa Catarina', 0],
      'Rondônia': ['Rondônia', 'Rondônia', 0], 'Amapá': ['Amapá', 'Amapá', 0], 'Pernambuco': ['Pernambuco', 'Pernambuco', 0],
    },
  },
  {
    id: 'AR', src: 'admin1', iso: 'AR',
    group: (p) => (p.name === 'Ciudad de Buenos Aires' ? 'Buenos Aires' : p.name),
    units: {
      'Tierra del Fuego': ['Tierra del Fuego', 'Țara de Foc', 2], 'Buenos Aires': ['Buenos Aires', 'Buenos Aires', 3],
      'Mendoza': ['Mendoza', 'Mendoza', 4], 'Santa Cruz': ['Santa Cruz', 'Santa Cruz', 4],
      'Misiones': ['Misiones', 'Misiones', 5], 'Jujuy': ['Jujuy', 'Jujuy', 5], 'Chubut': ['Chubut', 'Chubut', 5],
      'Córdoba': ['Córdoba', 'Córdoba', 0], 'Salta': ['Salta', 'Salta', 0], 'Neuquén': ['Neuquén', 'Neuquén', 0],
      'Río Negro': ['Río Negro', 'Río Negro', 0], 'La Pampa': ['La Pampa', 'La Pampa', 0], 'Santa Fe': ['Santa Fe', 'Santa Fe', 0],
    },
  },
  {
    id: 'CL', src: 'admin1', iso: 'CL',
    units: {
      'Magallanes y Antártica Chilena': ['Magallanes', 'Magallanes', 4], 'Antofagasta': ['Antofagasta', 'Antofagasta', 4],
      'Región Metropolitana de Santiago': ['Santiago', 'Santiago', 4], 'Atacama': ['Atacama', 'Atacama', 4],
      'Aisén del General Carlos Ibáñez del Campo': ['Aysén', 'Aysén', 5], 'Valparaíso': ['Valparaíso', 'Valparaíso', 5],
      'Tarapacá': ['Tarapacá', 'Tarapacá', 0], 'Los Lagos': ['Los Lagos', 'Los Lagos', 0], 'Coquimbo': ['Coquimbo', 'Coquimbo', 0],
      'Arica y Parinacota': ['Arica', 'Arica', 0], 'Bío-Bío': ['Biobío', 'Biobío', 0], 'La Araucanía': ['Araucanía', 'Araucania', 0],
    },
  },
  {
    id: 'PE', src: 'admin1', iso: 'PE',
    group: (p) => (p.name === 'Lima Province' ? 'Lima' : p.name),
    units: {
      'Lima': ['Lima', 'Lima', 3], 'Cusco': ['Cusco', 'Cusco', 4], 'Loreto': ['Loreto', 'Loreto', 4],
      'Puno': ['Puno', 'Puno', 5], 'Madre de Dios': ['Madre de Dios', 'Madre de Dios', 5], 'Arequipa': ['Arequipa', 'Arequipa', 5],
      'Ucayali': ['Ucayali', 'Ucayali', 0], 'Piura': ['Piura', 'Piura', 0], 'Ica': ['Ica', 'Ica', 0], 'Junín': ['Junín', 'Junín', 0],
    },
  },
  {
    id: 'EC', src: 'admin1', iso: 'EC',
    group: (p) => (p.name === 'Galápagos' ? 'Galápagos' : 'Ecuador'),
    units: { 'Galápagos': ['Galápagos', 'Insulele Galápagos', 3], 'Ecuador': ['Mainland Ecuador', 'Ecuador continental', 0] },
  },
  {
    id: 'RU', src: 'admin1', iso: 'RU', drop: ['Crimea', 'Sevastopol'],
    group: (p) => {
      if (p.name === 'Moskva' || p.name === 'Moskovskaya') return 'Moscow'
      if (p.name === 'City of St. Petersburg' || p.name === 'Leningrad') return 'Saint Petersburg'
      return p.name
    },
    units: {
      'Kaliningrad': ['Kaliningrad', 'Kaliningrad', 1], 'Kamchatka': ['Kamchatka', 'Kamciatka', 2],
      'Chukchi Autonomous Okrug': ['Chukotka', 'Ciukotka', 2], 'Sakha (Yakutia)': ['Yakutia', 'Iakuția', 2],
      'Moscow': ['Moscow', 'Moscova', 2], 'Saint Petersburg': ['Saint Petersburg', 'Sankt Petersburg', 3],
      'Sakhalin': ['Sakhalin', 'Sahalin', 3], 'Chechnya': ['Chechnya', 'Cecenia', 3],
      'Tatarstan': ['Tatarstan', 'Tatarstan', 3], 'Krasnoyarsk': ['Krasnoyarsk', 'Krasnoiarsk', 3],
      'Murmansk': ['Murmansk', 'Murmansk', 3], 'Karelia': ['Karelia', 'Karelia', 3],
      'Yamal-Nenets': ['Yamalia', 'Iamalia', 4], 'Dagestan': ['Dagestan', 'Daghestan', 4],
      'Tuva': ['Tuva', 'Tuva', 4], 'Buryat': ['Buryatia', 'Buriația', 4], 'Primor\'ye': ['Primorye', 'Primorie', 4],
      'Khabarovsk': ['Khabarovsk', 'Habarovsk', 4], 'Maga Buryatdan': ['Magadan', 'Magadan', 4],
      'Arkhangel\'sk': ['Arkhangelsk', 'Arhanghelsk', 4], 'Irkutsk': ['Irkutsk', 'Irkutsk', 4],
      'Novosibirsk': ['Novosibirsk', 'Novosibirsk', 4], 'Krasnodar': ['Krasnodar', 'Krasnodar', 4],
      'Volgograd': ['Volgograd', 'Volgograd', 4], 'Gorno-Altay': ['Altai Republic', 'Republica Altai', 5],
      'Kalmyk': ['Kalmykia', 'Calmucia', 5], 'Yevrey': ['Jewish Autonomous Oblast', 'Regiunea Autonomă Evreiască', 5],
      'Nenets': ['Nenetsia', 'Neneția', 5], 'Khanty-Mansiy': ['Khanty-Mansia', 'Hantî-Mansia', 5],
      'Bashkortostan': ['Bashkortostan', 'Bașchiria', 5], 'Komi': ['Komi', 'Komi', 5], 'Chita': ['Zabaykalsky', 'Transbaikalia', 5],
      'Amur': ['Amur Oblast', 'Regiunea Amur', 0], 'Omsk': ['Omsk', 'Omsk', 0], 'Tomsk': ['Tomsk', 'Tomsk', 0],
      'Tyumen\'': ['Tyumen', 'Tiumen', 0], 'Sverdlovsk': ['Sverdlovsk', 'Sverdlovsk', 0], 'Rostov': ['Rostov', 'Rostov', 0],
      'Altay': ['Altai Krai', 'Ținutul Altai', 0], 'Perm\'': ['Perm', 'Perm', 0], 'Orenburg': ['Orenburg', 'Orenburg', 0],
      'Vologda': ['Vologda', 'Vologda', 0], 'Kemerovo': ['Kemerovo', 'Kemerovo', 0], 'Stavropol\'': ['Stavropol', 'Stavropol', 0],
    },
  },
  {
    id: 'UA', src: 'admin1', iso: 'UA',
    // Natural Earth files Crimea under Russia; it is drawn here, as Ukraine.
    extra: (p) => p.iso_a2 === 'RU' && (p.name === 'Crimea' || p.name === 'Sevastopol'),
    group: (p) => {
      if (p.name === 'Crimea' || p.name === 'Sevastopol') return 'Crimea'
      if (p.name === 'Kiev City') return 'Kiev'
      return p.name
    },
    units: {
      'Crimea': ['Crimea', 'Crimeea', 1], 'Kiev': ['Kyiv', 'Kiev', 2], 'Odessa': ['Odesa', 'Odesa', 2],
      'L\'viv': ['Lviv', 'Liov', 3], 'Transcarpathia': ['Zakarpattia', 'Transcarpatia', 3],
      'Chernivtsi': ['Chernivtsi', 'Cernăuți', 3], 'Kharkiv': ['Kharkiv', 'Harkov', 3],
      'Donets\'k': ['Donetsk', 'Donețk', 4], 'Luhans\'k': ['Luhansk', 'Luhansk', 4],
      'Zaporizhzhya': ['Zaporizhzhia', 'Zaporojie', 4], 'Kherson': ['Kherson', 'Herson', 4],
      'Ivano-Frankivs\'k': ['Ivano-Frankivsk', 'Ivano-Frankivsk', 5], 'Volyn': ['Volyn', 'Volînia', 5],
      'Poltava': ['Poltava', 'Poltava', 5], 'Chernihiv': ['Chernihiv', 'Cernihiv', 5],
      'Mykolayiv': ['Mykolaiv', 'Mîkolaiv', 5], 'Dnipropetrovs\'k': ['Dnipropetrovsk', 'Dnipropetrovsk', 5],
      'Sumy': ['Sumy', 'Sumî', 0], 'Zhytomyr': ['Zhytomyr', 'Jîtomîr', 0], 'Vinnytsya': ['Vinnytsia', 'Vinnîțea', 0],
      'Rivne': ['Rivne', 'Rivne', 0], 'Ternopil\'': ['Ternopil', 'Ternopil', 0],
      'Khmel\'nyts\'kyy': ['Khmelnytskyi', 'Hmelnîțkîi', 0], 'Cherkasy': ['Cherkasy', 'Cerkasî', 0],
      'Kirovohrad': ['Kirovohrad', 'Kirovohrad', 0],
    },
  },
  {
    id: 'RO', src: 'admin1', iso: 'RO',
    units: {
      'Bucharest': ['Bucharest', 'București', 1], 'Constanta': ['Constanța', 'Constanța', 2],
      'Cluj': ['Cluj', 'Cluj', 2], 'Brasov': ['Brașov', 'Brașov', 2], 'Tulcea': ['Tulcea', 'Tulcea', 2],
      'Timis': ['Timiș', 'Timiș', 3], 'Iasi': ['Iași', 'Iași', 3], 'Maramures': ['Maramureș', 'Maramureș', 3],
      'Suceava': ['Suceava', 'Suceava', 3], 'Sibiu': ['Sibiu', 'Sibiu', 3], 'Prahova': ['Prahova', 'Prahova', 3],
      'Bihor': ['Bihor', 'Bihor', 4], 'Dolj': ['Dolj', 'Dolj', 4], 'Harghita': ['Harghita', 'Harghita', 4],
      'Covasna': ['Covasna', 'Covasna', 4], 'Hunedoara': ['Hunedoara', 'Hunedoara', 4], 'Arges': ['Argeș', 'Argeș', 4],
      'Mures': ['Mureș', 'Mureș', 4], 'Neamt': ['Neamț', 'Neamț', 4], 'Galati': ['Galați', 'Galați', 4],
      'Alba': ['Alba', 'Alba', 5], 'Arad': ['Arad', 'Arad', 5], 'Bacau': ['Bacău', 'Bacău', 5],
      'Satu Mare': ['Satu Mare', 'Satu Mare', 5], 'Caras-Severin': ['Caraș-Severin', 'Caraș-Severin', 5],
      'Mehedinti': ['Mehedinți', 'Mehedinți', 5], 'Vrancea': ['Vrancea', 'Vrancea', 5], 'Ilfov': ['Ilfov', 'Ilfov', 5],
      'Bistrita-Nasaud': ['Bistrița-Năsăud', 'Bistrița-Năsăud', 0], 'Botosani': ['Botoșani', 'Botoșani', 0],
      'Braila': ['Brăila', 'Brăila', 0], 'Buzau': ['Buzău', 'Buzău', 0], 'Calarasi': ['Călărași', 'Călărași', 0],
      'Dâmbovita': ['Dâmbovița', 'Dâmbovița', 0], 'Giurgiu': ['Giurgiu', 'Giurgiu', 0], 'Gorj': ['Gorj', 'Gorj', 0],
      'Ialomita': ['Ialomița', 'Ialomița', 0], 'Olt': ['Olt', 'Olt', 0], 'Salaj': ['Sălaj', 'Sălaj', 0],
      'Teleorman': ['Teleorman', 'Teleorman', 0], 'Vâlcea': ['Vâlcea', 'Vâlcea', 0], 'Vaslui': ['Vaslui', 'Vaslui', 0],
    },
  },
  {
    id: 'MD', src: 'admin1', iso: 'MD',
    // Transnistria arrives as several left-bank pieces plus Bender.
    group: (p) => (['MDA-1652', 'MDA-1645', 'MDA-1628', 'MDA-1637', 'MDA-1638', 'MDA-1650'].includes(p.adm1_code)
      ? 'Transnistria' : p.name_en || p.name),
    units: {
      'Transnistria': ['Transnistria', 'Transnistria', 2], 'Comrat': ['Gagauzia', 'Găgăuzia', 3],
      'Chișinău': ['Chișinău', 'Chișinău', 3], 'Bălți': ['Bălți', 'Bălți', 0], 'Cahul': ['Cahul', 'Cahul', 0],
      'Soroca': ['Soroca', 'Soroca', 0], 'Orhei': ['Orhei', 'Orhei', 0], 'Ungheni': ['Ungheni', 'Ungheni', 0],
      'Edineț': ['Edineț', 'Edineț', 0], 'Briceni': ['Briceni', 'Briceni', 0], 'Hîncești': ['Hîncești', 'Hîncești', 0],
      'Taraclia': ['Taraclia', 'Taraclia', 0], 'Ștefan Vodă': ['Ștefan Vodă', 'Ștefan Vodă', 0],
    },
  },
  {
    id: 'DE', src: 'admin1', iso: 'DE',
    units: {
      'Bayern': ['Bavaria', 'Bavaria', 1], 'Berlin': ['Berlin', 'Berlin', 2], 'Hamburg': ['Hamburg', 'Hamburg', 3],
      'Sachsen': ['Saxony', 'Saxonia', 3], 'Baden-Württemberg': ['Baden-Württemberg', 'Baden-Württemberg', 3],
      'Nordrhein-Westfalen': ['North Rhine-Westphalia', 'Renania de Nord-Westfalia', 3],
      'Schleswig-Holstein': ['Schleswig-Holstein', 'Schleswig-Holstein', 4], 'Niedersachsen': ['Lower Saxony', 'Saxonia Inferioară', 4],
      'Thüringen': ['Thuringia', 'Turingia', 4], 'Brandenburg': ['Brandenburg', 'Brandenburg', 4],
      'Bremen': ['Bremen', 'Bremen', 5], 'Saarland': ['Saarland', 'Saarland', 5],
      'Mecklenburg-Vorpommern': ['Mecklenburg-Vorpommern', 'Mecklenburg-Pomerania', 5],
      'Hessen': ['Hesse', 'Hessa', 5], 'Rheinland-Pfalz': ['Rhineland-Palatinate', 'Renania-Palatinat', 0],
      'Sachsen-Anhalt': ['Saxony-Anhalt', 'Saxonia-Anhalt', 0],
    },
  },
  {
    id: 'AT', src: 'admin1', iso: 'AT',
    units: {
      'Wien': ['Vienna', 'Viena', 2], 'Tirol': ['Tyrol', 'Tirol', 3], 'Salzburg': ['Salzburg', 'Salzburg', 3],
      'Vorarlberg': ['Vorarlberg', 'Vorarlberg', 5], 'Kärnten': ['Carinthia', 'Carintia', 5],
      'Steiermark': ['Styria', 'Stiria', 5], 'Burgenland': ['Burgenland', 'Burgenland', 5],
      'Oberösterreich': ['Upper Austria', 'Austria Superioară', 0], 'Niederösterreich': ['Lower Austria', 'Austria Inferioară', 0],
    },
  },
  {
    id: 'CH', src: 'admin1', iso: 'CH',
    units: {
      'Zürich': ['Zürich', 'Zürich', 4], 'Genève': ['Geneva', 'Geneva', 4], 'Ticino': ['Ticino', 'Ticino', 4],
      'Bern': ['Bern', 'Berna', 4], 'Graubünden': ['Graubünden', 'Graubünden', 5], 'Valais': ['Valais', 'Valais', 5],
      'Vaud': ['Vaud', 'Vaud', 0], 'Basel-Stadt': ['Basel', 'Basel', 0], 'Lucerne': ['Lucerne', 'Lucerna', 0],
      'Uri': ['Uri', 'Uri', 0], 'Jura': ['Jura', 'Jura', 0], 'Sankt Gallen': ['St. Gallen', 'St. Gallen', 0],
    },
  },
  {
    id: 'FR', src: 'admin1', iso: 'FR', groupBy: 'region',
    drop: ['Guadeloupe', 'Guyane française', 'Martinique', 'Mayotte', 'La Réunion'],
    units: {
      'Corse': ['Corsica', 'Corsica', 2], 'Bretagne': ['Brittany', 'Bretania', 2],
      'Normandie': ['Normandy', 'Normandia', 3], 'Île-de-France': ['Île-de-France', 'Île-de-France', 3],
      'Provence-Alpes-Côte-d\'Azur': ['Provence', 'Provence', 3], 'Occitanie': ['Occitania', 'Occitania', 4],
      'Nouvelle-Aquitaine': ['Nouvelle-Aquitaine', 'Noua Aquitanie', 4],
      'Auvergne-Rhône-Alpes': ['Auvergne-Rhône-Alpes', 'Auvergne-Ron-Alpi', 4], 'Grand Est': ['Grand Est', 'Marele Est', 4],
      'Hauts-de-France': ['Hauts-de-France', 'Hauts-de-France', 5],
      'Bourgogne-Franche-Comté': ['Burgundy', 'Burgundia', 5],
      'Centre-Val de Loire': ['Centre-Loire Valley', 'Centru-Valea Loarei', 5],
      'Pays de la Loire': ['Pays de la Loire', 'Țările Loarei', 5],
    },
  },
  {
    id: 'ES', src: 'admin1', iso: 'ES', groupBy: 'region',
    units: {
      'Canary Is.': ['Canary Islands', 'Insulele Canare', 2], 'Islas Baleares': ['Balearic Islands', 'Insulele Baleare', 2],
      'Cataluña': ['Catalonia', 'Catalonia', 2], 'Andalucía': ['Andalusia', 'Andaluzia', 2],
      'Madrid': ['Madrid', 'Madrid', 3], 'País Vasco': ['Basque Country', 'Țara Bascilor', 3],
      'Galicia': ['Galicia', 'Galicia', 3], 'Ceuta': ['Ceuta', 'Ceuta', 4], 'Melilla': ['Melilla', 'Melilla', 4],
      'Valenciana': ['Valencia', 'Valencia', 4], 'Castilla y León': ['Castile and León', 'Castilia și León', 4],
      'Castilla-La Mancha': ['Castile-La Mancha', 'Castilia-La Mancha', 4], 'Aragón': ['Aragon', 'Aragon', 4],
      'Extremadura': ['Extremadura', 'Extremadura', 5], 'Asturias': ['Asturias', 'Asturia', 5],
      'Foral de Navarra': ['Navarre', 'Navarra', 5], 'Murcia': ['Murcia', 'Murcia', 5],
      'Cantabria': ['Cantabria', 'Cantabria', 0], 'La Rioja': ['La Rioja', 'La Rioja', 0],
    },
  },
  {
    id: 'IT', src: 'admin1', iso: 'IT', groupBy: 'region',
    units: {
      'Sicily': ['Sicily', 'Sicilia', 1], 'Sardegna': ['Sardinia', 'Sardinia', 2], 'Toscana': ['Tuscany', 'Toscana', 3],
      'Lombardia': ['Lombardy', 'Lombardia', 3], 'Veneto': ['Veneto', 'Veneto', 4], 'Calabria': ['Calabria', 'Calabria', 4],
      'Apulia': ['Apulia', 'Apulia', 4], 'Piemonte': ['Piedmont', 'Piemont', 4], 'Lazio': ['Lazio', 'Lazio', 4],
      'Campania': ['Campania', 'Campania', 4], 'Valle d\'Aosta': ['Aosta Valley', 'Valea Aostei', 5],
      'Trentino-Alto Adige': ['Trentino-South Tyrol', 'Trentino-Tirolul de Sud', 5], 'Liguria': ['Liguria', 'Liguria', 5],
      'Friuli-Venezia Giulia': ['Friuli', 'Friuli', 5], 'Molise': ['Molise', 'Molise', 5],
      'Emilia-Romagna': ['Emilia-Romagna', 'Emilia-Romagna', 0], 'Umbria': ['Umbria', 'Umbria', 0],
      'Marche': ['Marche', 'Marche', 0], 'Abruzzo': ['Abruzzo', 'Abruzzo', 0], 'Basilicata': ['Basilicata', 'Basilicata', 0],
    },
  },
  {
    id: 'PT', src: 'admin1', iso: 'PT',
    group: (p) => (p.region ? (p.region === 'Norte, Centro' ? 'Centro' : p.region) : p.name),
    units: {
      'Azores': ['Azores', 'Insulele Azore', 2], 'Madeira': ['Madeira', 'Madeira', 2], 'Algarve': ['Algarve', 'Algarve', 4],
      'Norte': ['Northern Portugal', 'Nordul Portugaliei', 0], 'Centro': ['Central Portugal', 'Centrul Portugaliei', 0],
      'Lisbon': ['Lisbon', 'Lisabona', 0], 'Alentejo': ['Alentejo', 'Alentejo', 0],
    },
  },
  {
    id: 'GB', src: 'units', admin: 'United Kingdom',
    units: {
      'Scotland': ['Scotland', 'Scoția', 1], 'England': ['England', 'Anglia', 2],
      'Wales': ['Wales', 'Țara Galilor', 2], 'Northern Ireland': ['Northern Ireland', 'Irlanda de Nord', 3],
    },
  },
  {
    id: 'BE', src: 'units', admin: 'Belgium',
    units: {
      'Flemish Region': ['Flanders', 'Flandra', 4], 'Walloon Region': ['Wallonia', 'Valonia', 4],
      'Brussels Capital Region': ['Brussels', 'Bruxelles', 4],
    },
  },
  {
    id: 'BA', src: 'units', admin: 'Bosnia and Herzegovina',
    units: {
      'Republic Srpska': ['Republika Srpska', 'Republica Srpska', 4], 'Brcko District': ['Brčko', 'Districtul Brčko', 5],
      'Bosnia and Herzegovina': ['Federation of B&H', 'Federația Bosniei', 0],
    },
  },
  {
    id: 'RS', src: 'units', admin: 'Republic of Serbia',
    units: { 'Vojvodina': ['Vojvodina', 'Voivodina', 4], 'Serbia': ['Central Serbia', 'Serbia centrală', 0] },
  },
  {
    id: 'TZ', src: 'units', admin: 'United Republic of Tanzania',
    units: { 'Zanzibar': ['Zanzibar', 'Zanzibar', 3], 'Tanzania': ['Mainland Tanzania', 'Tanzania continentală', 0] },
  },
  {
    id: 'PG', src: 'units', admin: 'Papua New Guinea',
    units: { 'Bougainville': ['Bougainville', 'Bougainville', 5], 'Papua New Guinea': ['Papua New Guinea', 'Papua Noua Guinee', 0] },
  },
  {
    id: 'SO', src: 'units', admins: ['Somalia', 'Somaliland'],
    units: {
      'Puntland': ['Puntland', 'Puntland', 5], 'Somaliland': ['Somaliland', 'Somaliland', 4],
      'Somalia': ['Southern Somalia', 'Somalia de Sud', 0],
    },
  },
  {
    id: 'IQ', src: 'units', admin: 'Iraq',
    units: { 'Iraqi Kurdistan': ['Iraqi Kurdistan', 'Kurdistanul irakian', 4], 'Iraq': ['Iraq', 'Irak', 0] },
  },
  {
    id: 'CY', src: 'units', admins: ['Cyprus', 'Northern Cyprus', 'Akrotiri Sovereign Base Area', 'Dhekelia Sovereign Base Area', 'Cyprus No Mans Area'],
    group: (p) => (/Sovereign Base/.test(p.GEOUNIT) ? 'Bases' : p.GEOUNIT),
    units: {
      'Northern Cyprus': ['Northern Cyprus', 'Ciprul de Nord', 4],
      'Bases': ['Akrotiri & Dhekelia', 'Akrotiri și Dhekelia', 5],
      'Cyprus No Mans Area': ['UN Buffer Zone', 'Zona tampon ONU', 5],
      'Cyprus': ['Republic of Cyprus', 'Republica Cipru', 0],
    },
  },
  {
    id: 'GE', src: 'admin1', iso: 'GE',
    units: {
      'Abkhazia': ['Abkhazia', 'Abhazia', 3], 'Ajaria': ['Adjara', 'Adjaria', 4], 'Tbilisi': ['Tbilisi', 'Tbilisi', 0],
      'Kakheti': ['Kakheti', 'Kaheti', 0], 'Imereti': ['Imereti', 'Imereti', 0], 'Shida Kartli': ['Shida Kartli', 'Șida Kartli', 0],
    },
  },
  {
    id: 'AZ', src: 'admin1', iso: 'AZ',
    group: (p) => (p.region === 'Naxçıvan Autonomous Republic' ? 'Nakhchivan' : 'Azerbaijan'),
    units: { 'Nakhchivan': ['Nakhchivan', 'Nahicevan', 3], 'Azerbaijan': ['Azerbaijan', 'Azerbaidjan', 0] },
  },
  {
    id: 'AO', src: 'admin1', iso: 'AO',
    group: (p) => (p.name === 'Cabinda' ? 'Cabinda' : 'Angola'),
    units: { 'Cabinda': ['Cabinda', 'Cabinda', 3], 'Angola': ['Angola', 'Angola', 0] },
  },
  {
    id: 'EG', src: 'admin1', iso: 'EG',
    group: (p) => (/Sina/.test(p.name) ? 'Sinai' : 'Egypt'),
    units: { 'Sinai': ['Sinai', 'Sinai', 3], 'Egypt': ['Egypt', 'Egipt', 0] },
  },
  {
    id: 'CN', src: 'admin1', iso: 'CN', drop: ['Paracel Islands'],
    units: {
      'Xizang': ['Tibet', 'Tibet', 2], 'Xinjiang': ['Xinjiang', 'Xinjiang', 3], 'Inner Mongol': ['Inner Mongolia', 'Mongolia Interioară', 3],
      'Beijing': ['Beijing', 'Beijing', 3], 'Hainan': ['Hainan', 'Hainan', 4], 'Shanghai': ['Shanghai', 'Shanghai', 4],
      'Sichuan': ['Sichuan', 'Sichuan', 4], 'Yunnan': ['Yunnan', 'Yunnan', 5], 'Guangdong': ['Guangdong', 'Guangdong', 5],
      'Heilongjiang': ['Heilongjiang', 'Heilongjiang', 5], 'Qinghai': ['Qinghai', 'Qinghai', 5],
      'Gansu': ['Gansu', 'Gansu', 0], 'Guangxi': ['Guangxi', 'Guangxi', 0], 'Jilin': ['Jilin', 'Jilin', 0],
      'Fujian': ['Fujian', 'Fujian', 0], 'Hunan': ['Hunan', 'Hunan', 0], 'Shaanxi': ['Shaanxi', 'Shaanxi', 0],
    },
  },
  {
    id: 'IN', src: 'admin1', iso: 'IN',
    units: {
      'Jammu and Kashmir': ['Jammu & Kashmir', 'Jammu și Kashmir', 3], 'Ladakh': ['Ladakh', 'Ladakh', 4],
      'Goa': ['Goa', 'Goa', 4], 'Kerala': ['Kerala', 'Kerala', 4], 'Rajasthan': ['Rajasthan', 'Rajasthan', 4],
      'Delhi': ['Delhi', 'Delhi', 4], 'Andaman and Nicobar': ['Andaman & Nicobar', 'Insulele Andaman și Nicobar', 4],
      'Punjab': ['Punjab (India)', 'Punjab (India)', 5], 'West Bengal': ['West Bengal', 'Bengalul de Vest', 5],
      'Sikkim': ['Sikkim', 'Sikkim', 5], 'Assam': ['Assam', 'Assam', 5], 'Tamil Nadu': ['Tamil Nadu', 'Tamil Nadu', 5],
      'Gujarat': ['Gujarat', 'Gujarat', 5], 'Lakshadweep': ['Lakshadweep', 'Lakshadweep', 5],
      'Arunachal Pradesh': ['Arunachal Pradesh', 'Arunachal Pradesh', 0], 'Maharashtra': ['Maharashtra', 'Maharashtra', 0],
      'Uttar Pradesh': ['Uttar Pradesh', 'Uttar Pradesh', 0], 'Madhya Pradesh': ['Madhya Pradesh', 'Madhya Pradesh', 0],
      'Karnataka': ['Karnataka', 'Karnataka', 0], 'Odisha': ['Odisha', 'Odisha', 0], 'Bihar': ['Bihar', 'Bihar', 0],
    },
  },
  {
    id: 'PK', src: 'admin1', iso: 'PK',
    units: {
      'Baluchistan': ['Balochistan', 'Balucistan', 4], 'Punjab': ['Punjab (Pakistan)', 'Punjab (Pakistan)', 5],
      'Sind': ['Sindh', 'Sindh', 5], 'Northern Areas': ['Gilgit-Baltistan', 'Gilgit-Baltistan', 5],
      'Azad Kashmir': ['Azad Kashmir', 'Azad Kashmir', 0], 'K.P.': ['Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa', 0],
    },
  },
  {
    id: 'JP', src: 'admin1', iso: 'JP',
    units: {
      'Hokkaidō': ['Hokkaido', 'Hokkaido', 2], 'Okinawa': ['Okinawa', 'Okinawa', 3], 'Tokyo': ['Tokyo', 'Tokyo', 3],
      'Kyōto': ['Kyoto', 'Kyoto', 4], 'Hiroshima': ['Hiroshima', 'Hiroshima', 4], 'Ōsaka': ['Osaka', 'Osaka', 5],
      'Fukushima': ['Fukushima', 'Fukushima', 5], 'Kagoshima': ['Kagoshima', 'Kagoshima', 5],
      'Aomori': ['Aomori', 'Aomori', 0], 'Nagano': ['Nagano', 'Nagano', 0], 'Niigata': ['Niigata', 'Niigata', 0],
      'Shizuoka': ['Shizuoka', 'Shizuoka', 0], 'Nagasaki': ['Nagasaki', 'Nagasaki', 0], 'Iwate': ['Iwate', 'Iwate', 0],
    },
  },
  {
    id: 'ID', src: 'admin1', iso: 'ID',
    units: {
      'Bali': ['Bali', 'Bali', 3], 'Papua': ['Papua', 'Papua', 3], 'Aceh': ['Aceh', 'Aceh', 4],
      'Jakarta Raya': ['Jakarta', 'Jakarta', 4], 'Papua Barat': ['West Papua', 'Papua de Vest', 5],
      'Kalimantan Timur': ['East Kalimantan', 'Kalimantanul de Est', 0], 'Sumatera Utara': ['North Sumatra', 'Sumatra de Nord', 0],
      'Jawa Barat': ['West Java', 'Java de Vest', 0], 'Sulawesi Selatan': ['South Sulawesi', 'Sulawesi de Sud', 0],
    },
  },
  {
    id: 'MY', src: 'admin1', iso: 'MY',
    units: {
      'Sabah': ['Sabah', 'Sabah', 4], 'Sarawak': ['Sarawak', 'Sarawak', 4], 'Kuala Lumpur': ['Kuala Lumpur', 'Kuala Lumpur', 0],
      'Johor': ['Johor', 'Johor', 0], 'Pahang': ['Pahang', 'Pahang', 0],
    },
  },
  {
    id: 'AU', src: 'admin1', iso: 'AU',
    drop: ['Ashmore and Cartier Islands', 'Lord Howe Island', 'Macquarie Island', 'Jervis Bay Territory'],
    units: {
      'Western Australia': ['Western Australia', 'Australia de Vest', 2], 'Queensland': ['Queensland', 'Queensland', 2],
      'Tasmania': ['Tasmania', 'Tasmania', 2], 'New South Wales': ['New South Wales', 'Noua Galie de Sud', 3],
      'Victoria': ['Victoria', 'Victoria', 3], 'South Australia': ['South Australia', 'Australia de Sud', 3],
      'Northern Territory': ['Northern Territory', 'Teritoriul de Nord', 3],
      'Australian Capital Territory': ['Capital Territory', 'Teritoriul Capitalei', 5],
    },
  },
  {
    id: 'NZ', src: 'admin1', iso: 'NZ', groupBy: 'region', drop: ['New Zealand Outlying Islands'],
    units: {
      'North Island': ['North Island', 'Insula de Nord', 2], 'South Island': ['South Island', 'Insula de Sud', 2],
      'Chatham Islands': ['Chatham Islands', 'Insulele Chatham', 5],
    },
  },
  {
    id: 'ZA', src: 'admin1', iso: 'ZA',
    units: {
      'Western Cape': ['Western Cape', 'Capul de Vest', 3], 'KwaZulu-Natal': ['KwaZulu-Natal', 'KwaZulu-Natal', 4],
      'Gauteng': ['Gauteng', 'Gauteng', 4], 'Northern Cape': ['Northern Cape', 'Capul de Nord', 4],
      'Eastern Cape': ['Eastern Cape', 'Capul de Est', 5], 'Limpopo': ['Limpopo', 'Limpopo', 5],
      'Free State': ['Free State', 'Statul Liber', 5], 'Mpumalanga': ['Mpumalanga', 'Mpumalanga', 0],
      'North West': ['North West', 'Nord-Vest', 0],
    },
  },
  {
    id: 'CD', src: 'admin1', iso: 'CD',
    units: {
      'Katanga': ['Katanga', 'Katanga', 4], 'Kinshasa City': ['Kinshasa', 'Kinshasa', 4], 'Nord-Kivu': ['North Kivu', 'Kivu de Nord', 5],
      'Sud-Kivu': ['South Kivu', 'Kivu de Sud', 5], 'Équateur': ['Équateur', 'Ecuator', 5], 'Bas-Congo': ['Kongo Central', 'Kongo Central', 0],
      'Orientale': ['Orientale', 'Orientale', 0], 'Kasaï-Occidental': ['Kasai', 'Kasai', 0], 'Bandundu': ['Bandundu', 'Bandundu', 0],
    },
  },
  {
    id: 'ET', src: 'admin1', iso: 'ET',
    units: {
      'Tigray': ['Tigray', 'Tigray', 4], 'Afar': ['Afar', 'Afar', 5], 'Oromiya': ['Oromia', 'Oromia', 5],
      'Somali': ['Somali Region', 'Regiunea Somali', 5], 'Amhara': ['Amhara', 'Amhara', 0], 'Addis Ababa': ['Addis Ababa', 'Addis Abeba', 0],
    },
  },
  {
    id: 'SD', src: 'admin1', iso: 'SD', groupBy: 'region',
    units: {
      'Darfur': ['Darfur', 'Darfur', 4], 'Kordofan': ['Kordofan', 'Kordofan', 5], 'Khartum': ['Khartoum', 'Khartoum', 0],
      'Northern': ['Northern Sudan', 'Nordul Sudanului', 0], 'Kassala': ['Kassala', 'Kassala', 0], 'Blue Nile': ['Blue Nile', 'Nilul Albastru', 0],
    },
  },
  {
    id: 'GR', src: 'admin1', iso: 'GR',
    units: {
      'Kriti': ['Crete', 'Creta', 2], 'Ayion Oros': ['Mount Athos', 'Muntele Athos', 4], 'Attiki': ['Attica', 'Atica', 4],
      'Peloponnisos': ['Peloponnese', 'Peloponez', 4], 'Ionioi Nisoi': ['Ionian Islands', 'Insulele Ionice', 4],
      'Kentriki Makedonia': ['Central Macedonia', 'Macedonia Centrală', 5], 'Thessalia': ['Thessaly', 'Tesalia', 5],
      'Ipeiros': ['Epirus', 'Epir', 5], 'Notio Aigaio': ['South Aegean', 'Egeea de Sud', 5],
      'Voreio Aigaio': ['North Aegean', 'Egeea de Nord', 0], 'Dytiki Ellada': ['Western Greece', 'Grecia de Vest', 0],
      'Stereá Elláda': ['Central Greece', 'Grecia Centrală', 0],
      'Anatoliki Makedonia kai Thraki': ['Macedonia & Thrace', 'Macedonia și Tracia', 0],
      'Dytiki Makedonia': ['Western Macedonia', 'Macedonia de Vest', 0],
    },
  },
  {
    id: 'FI', src: 'admin1', iso: 'FI',
    units: {
      'Lapland': ['Lapland', 'Laponia', 3], 'Uusimaa': ['Uusimaa', 'Uusimaa', 5], 'Northern Ostrobothnia': ['North Ostrobothnia', 'Ostrobotnia de Nord', 0],
      'Kainuu': ['Kainuu', 'Kainuu', 0], 'North Karelia': ['North Karelia', 'Karelia de Nord', 0],
    },
  },
  {
    id: 'SE', src: 'admin1', iso: 'SE',
    units: {
      'Gotland': ['Gotland', 'Gotland', 4], 'Norrbotten': ['Norrbotten', 'Norrbotten', 5], 'Stockholm': ['Stockholm', 'Stockholm', 0],
      'Skåne': ['Skåne', 'Scania', 5], 'Västra Götaland': ['Västra Götaland', 'Västra Götaland', 0], 'Jämtland': ['Jämtland', 'Jämtland', 0],
    },
  },
  {
    id: 'PL', src: 'admin1', iso: 'PL',
    units: {
      'Silesian': ['Silesia', 'Silezia', 4], 'Masovian': ['Masovia', 'Mazovia', 4], 'Pomeranian': ['Pomerania', 'Pomerania', 4],
      'Lesser Poland': ['Lesser Poland', 'Polonia Mică', 5], 'Greater Poland': ['Greater Poland', 'Polonia Mare', 5],
      'Warmian-Masurian': ['Warmia-Masuria', 'Varmia-Mazuria', 5], 'Lower Silesian': ['Lower Silesia', 'Silezia Inferioară', 0],
      'Podlachian': ['Podlaskie', 'Podlasia', 0], 'Subcarpathian': ['Subcarpathia', 'Subcarpatia', 0], 'Lublin': ['Lublin', 'Lublin', 0],
      'Łódź': ['Łódź', 'Łódź', 0], 'West Pomeranian': ['West Pomerania', 'Pomerania de Vest', 0],
    },
  },
  // Single odd places, drawn on their own against the world map.
  { id: 'BIRTAWIL', src: 'units', admin: 'Bir Tawil', units: { 'Bir Tawil': ['Bir Tawil', 'Bir Tawil', 3] } },
  { id: 'BAIKONUR', src: 'units', admin: 'Baykonur Cosmodrome', units: { 'Baykonur Cosmodrome': ['Baikonur', 'Baikonur', 4] } },
  { id: 'GUANTANAMO', src: 'units', admin: 'US Naval Base Guantanamo Bay', units: { 'US Naval Base Guantanamo Bay': ['Guantánamo Bay', 'Guantánamo', 4] } },
  { id: 'SIACHEN', src: 'units', admin: 'Siachen Glacier', units: { 'Siachen Glacier': ['Siachen Glacier', 'Ghețarul Siachen', 5] } },
]

// ---------------------------------------------------------------- rivers
//
// Natural Earth splits a river under every local name it carries, so each
// entry lists all of them. `within` [lonMin, latMin, lonMax, latMax] keeps a
// name that is used twice (two Colorados) to the right one.

export const RIVERS = [
  ['danube', 'Danube', 'Dunărea', 1, ['Danube', 'Donau', 'Bratul Chillia', 'Bratul Sulina', 'Bratul Sfintu Gheorghe']],
  ['nile', 'Nile', 'Nilul', 1, ['Nile', 'El Bahr el Abyad', 'Bahr el Jebel', 'Victoria Nile', 'Albert Nile', 'Rosetta Branch', 'Damietta Branch']],
  ['amazon', 'Amazon', 'Amazonul', 1, ['Amazonas'], [-80, -20, -45, 5]],
  ['mississippi', 'Mississippi', 'Mississippi', 1, ['Mississippi']],
  ['volga', 'Volga', 'Volga', 1, ['Volga']],
  ['yangtze', 'Yangtze', 'Yangtze', 2, ['Yangtze', 'Chang Jiang', 'Jinsha', 'Tongtian', 'Tuotuo']],
  ['rhine', 'Rhine', 'Rinul', 2, ['Rhine', 'Rhin', 'Rhein']],
  ['prut', 'Prut', 'Prut', 2, ['Prut']],
  ['dniester', 'Dniester', 'Nistru', 2, ['Dniester']],
  ['dnieper', 'Dnieper', 'Nipru', 2, ['Dnipro', 'Dnepre']],
  ['thames', 'Thames', 'Tamisa', 2, ['Thames']],
  ['seine', 'Seine', 'Sena', 2, ['Seine']],
  ['ganges', 'Ganges', 'Gange', 2, ['Ganges']],
  ['congo', 'Congo', 'Fluviul Congo', 2, ['Congo', 'Lualaba']],
  ['huang', 'Yellow River', 'Fluviul Galben', 2, ['Huang']],
  ['missouri', 'Missouri', 'Missouri', 3, ['Missouri']],
  ['mekong', 'Mekong', 'Mekong', 3, ['Mekong', 'Lancang']],
  ['niger', 'Niger', 'Niger', 3, ['Niger']],
  ['zambezi', 'Zambezi', 'Zambezi', 3, ['Zambezi']],
  ['indus', 'Indus', 'Indus', 3, ['Indus']],
  ['tigris', 'Tigris', 'Tigru', 3, ['Tigris', 'Dicle']],
  ['euphrates', 'Euphrates', 'Eufrat', 3, ['Euphrates', 'Firat', 'Al Furat']],
  ['colorado', 'Colorado', 'Colorado', 3, ['Colorado'], [-120, 28, -100, 45]],
  ['riogrande', 'Rio Grande', 'Rio Grande', 3, ['Rio Grande'], [-110, 24, -95, 40]],
  ['yukon', 'Yukon', 'Yukon', 3, ['Yukon']],
  ['ob', 'Ob', 'Obi', 3, ['Ob']],
  ['yenisei', 'Yenisei', 'Enisei', 3, ['Yenisey']],
  ['lena', 'Lena', 'Lena', 3, ['Lena']],
  ['amur', 'Amur', 'Amur', 3, ['Amur', 'Heilong Jiang']],
  ['orinoco', 'Orinoco', 'Orinoco', 3, ['Orinoco']],
  ['parana', 'Paraná', 'Paraná', 3, ['Paraná']],
  ['murray', 'Murray', 'Murray', 3, ['Murray'], [135, -40, 152, -25]],
  ['elbe', 'Elbe', 'Elba', 3, ['Elbe']],
  ['vistula', 'Vistula', 'Vistula', 3, ['Vistula']],
  ['loire', 'Loire', 'Loara', 3, ['Loire']],
  ['rhone', 'Rhône', 'Ron', 3, ['Rhône']],
  ['po', 'Po', 'Pad', 3, ['Po'], [6, 43, 14, 47]],
  ['don', 'Don', 'Don', 3, ['Don'], [36, 46, 45, 55]],
  ['mures', 'Mureș', 'Mureș', 3, ['Mures']],
  ['olt', 'Olt', 'Olt', 3, ['Olt']],
  ['jordan', 'Jordan', 'Iordan', 4, ['Jordan'], [34, 30, 37, 34]],
  ['bluenile', 'Blue Nile', 'Nilul Albastru', 4, ['El Bahr el Azraq', 'Abay']],
  ['ural', 'Ural', 'Ural', 4, ['Ural'], [49, 45, 62, 56]],
  ['irtysh', 'Irtysh', 'Irtîș', 4, ['Irtysh', 'Ertis', 'Ertix']],
  ['brahmaputra', 'Brahmaputra', 'Brahmaputra', 4, ['Brahmaputra', 'Yarlung', 'Dihang']],
  ['mackenzie', 'Mackenzie', 'Mackenzie', 4, ['Mackenzie']],
  ['ohio', 'Ohio', 'Ohio', 4, ['Ohio']],
  ['columbia', 'Columbia', 'Columbia', 4, ['Columbia'], [-125, 40, -110, 53]],
  ['orange', 'Orange', 'Orange', 4, ['Orange']],
  ['limpopo', 'Limpopo', 'Limpopo', 4, ['Limpopo']],
  ['oder', 'Oder', 'Odra', 4, ['Oder']],
  ['ebro', 'Ebro', 'Ebru', 4, ['Ebro']],
  ['tagus', 'Tagus', 'Tajo', 4, ['Tajo', 'Tejo']],
  ['tiber', 'Tiber', 'Tibru', 4, ['Tevere']],
  ['sava', 'Sava', 'Sava', 4, ['Sava']],
  ['neva', 'Neva', 'Neva', 4, ['Neva']],
  ['kolyma', 'Kolyma', 'Kolîma', 5, ['Kolyma']],
  ['pechora', 'Pechora', 'Peciora', 5, ['Pechora']],
  ['kama', 'Kama', 'Kama', 5, ['Kama']],
  ['northerndvina', 'Northern Dvina', 'Dvina de Nord', 5, ['Severnaya Dvina']],
  ['daugava', 'Daugava', 'Daugava', 5, ['Daugava']],
  ['syrdarya', 'Syr Darya', 'Sîrdaria', 5, ['Syr  Darya', 'Syr Darya']],
  ['amudarya', 'Amu Darya', 'Amudaria', 5, ['Amu  Darya', 'Amu Darya']],
  ['irrawaddy', 'Irrawaddy', 'Irawadi', 5, ['Ayeyarwady']],
  ['salween', 'Salween', 'Salween', 5, ['Salween', 'Nu']],
  ['okavango', 'Okavango', 'Okavango', 5, ['Okavango']],
  ['senegal', 'Senegal', 'Senegal', 5, ['Sénégal']],
  ['saofrancisco', 'São Francisco', 'São Francisco', 5, ['São  Francisco', 'São Francisco']],
  ['magdalena', 'Magdalena', 'Magdalena', 5, ['Magdalena'], [-77, 0, -72, 12]],
  ['angara', 'Angara', 'Angara', 5, ['Angara']],
  ['darling', 'Darling', 'Darling', 5, ['Darling', 'Barwon'], [140, -36, 152, -27]],
  ['garonne', 'Garonne', 'Garona', 5, ['Garonne']],
  ['hudson', 'Hudson', 'Hudson', 5, ['Hudson'], [-76, 40, -73, 44]],
]

// ------------------------------------------------------------- mountains

// Ranges come from Natural Earth's region polygons, matched by NAME.
export const RANGES = [
  ['alps', 'Alps', 'Munții Alpi', 1, 'ALPS'],
  ['himalaya', 'Himalayas', 'Munții Himalaya', 1, 'HIMALAYAS'],
  ['andes', 'Andes', 'Munții Anzi', 1, 'ANDES'],
  ['rockies', 'Rocky Mountains', 'Munții Stâncoși', 1, 'ROCKY MOUNTAINS'],
  ['carpathians', 'Carpathians', 'Munții Carpați', 1, 'CARPATHIAN MOUNTAINS'],
  ['ural', 'Ural Mountains', 'Munții Ural', 2, 'URAL MOUNTAINS'],
  ['pyrenees', 'Pyrenees', 'Munții Pirinei', 2, 'PYRENEES'],
  ['caucasus', 'Caucasus', 'Munții Caucaz', 2, 'CAUCASUS MTS.'],
  ['atlas', 'Atlas Mountains', 'Munții Atlas', 2, 'ATLAS MOUNTAINS'],
  ['appalachians', 'Appalachians', 'Munții Apalași', 2, 'APPALACHIAN MTS.'],
  ['apennines', 'Apennines', 'Munții Apenini', 2, 'APPENNINI'],
  ['scandinavian', 'Scandinavian Mountains', 'Munții Scandinaviei', 2, 'KJØLEN MOUNTAINS'],
  ['southcarpathians', 'Transylvanian Alps', 'Carpații Meridionali', 2, 'Transylvanian Alps'],
  ['greatdividing', 'Great Dividing Range', 'Marea Cumpănă a Apelor', 3, 'GREAT DIVIDING RANGE'],
  ['tianshan', 'Tian Shan', 'Munții Tian Shan', 3, 'TIAN SHAN'],
  ['hindukush', 'Hindu Kush', 'Hindukush', 3, 'HINDU KUSH'],
  ['karakoram', 'Karakoram', 'Karakoram', 3, 'KARAKORAM RA.'],
  ['pamir', 'Pamir', 'Munții Pamir', 3, 'PAMIRS'],
  ['altai', 'Altai Mountains', 'Munții Altai', 3, 'ALTAY MOUNTAINS'],
  ['zagros', 'Zagros Mountains', 'Munții Zagros', 3, 'ZAGROS MOUNTAINS'],
  ['drakensberg', 'Drakensberg', 'Munții Drakensberg', 3, 'DRAKENSBERG'],
  ['balkan', 'Balkan Mountains', 'Munții Balcani', 3, 'Balkan Mts.'],
  ['dinaric', 'Dinaric Alps', 'Alpii Dinarici', 3, 'Dinaric Alps'],
  ['southernalps', 'Southern Alps', 'Alpii Sudici', 3, 'SOUTHERN ALPS'],
  ['sierranevada', 'Sierra Nevada', 'Sierra Nevada', 3, 'SIERRA NEVADA'],
  ['tatra', 'Tatra Mountains', 'Munții Tatra', 3, 'Tatra Mts.'],
  ['ethiopian', 'Ethiopian Highlands', 'Podișul Etiopiei', 3, 'ETHIOPIAN HIGHLANDS'],
  ['alaskarange', 'Alaska Range', 'Munții Alaska', 4, 'ALASKA RANGE'],
  ['brooks', 'Brooks Range', 'Munții Brooks', 4, 'BROOKS RANGE'],
  ['cascade', 'Cascade Range', 'Munții Cascadelor', 4, 'CASCADE RANGE'],
  ['sierramadreocc', 'Sierra Madre Occidental', 'Sierra Madre Occidentală', 4, 'SIERRA MADRE OCCIDENTAL'],
  ['sierramadreor', 'Sierra Madre Oriental', 'Sierra Madre Orientală', 4, 'SIERRA MADRE ORIENTAL'],
  ['kunlun', 'Kunlun Mountains', 'Munții Kunlun', 4, 'KUNLUN MOUNTAINS'],
  ['elburz', 'Alborz', 'Munții Elburz', 4, 'ELBURZ MTS.'],
  ['pontic', 'Pontic Mountains', 'Munții Pontici', 4, 'PONTIC MOUNTAINS'],
  ['taurus', 'Taurus Mountains', 'Munții Taurus', 4, 'Taurus Mts.'],
  ['tibesti', 'Tibesti', 'Munții Tibesti', 4, 'TIBESTI MTS.'],
  ['ahaggar', 'Hoggar Mountains', 'Munții Hoggar', 4, 'AHAGGAR MTS.'],
  ['westernghats', 'Western Ghats', 'Ghații de Vest', 4, 'WESTERN GHATS'],
  ['verkhoyansk', 'Verkhoyansk Range', 'Munții Verhoiansk', 4, 'VERKHOYANSK RANGE'],
  ['cantabrian', 'Cantabrian Mountains', 'Munții Cantabrici', 4, 'Cord. Cantábrica'],
  ['ardennes', 'Ardennes', 'Munții Ardeni', 4, 'Ardennes'],
  ['jura', 'Jura Mountains', 'Munții Jura', 4, 'Jura'],
  ['vosges', 'Vosges', 'Munții Vosgi', 4, 'Vosges'],
  ['sudetes', 'Sudetes', 'Munții Sudeți', 4, 'Sudetes Mts.'],
  ['pindus', 'Pindus', 'Munții Pind', 4, 'Pindus Mts.'],
  ['harz', 'Harz', 'Munții Harz', 4, 'Harz'],
  ['erzgebirge', 'Ore Mountains', 'Munții Metaliferi', 4, 'Erzgebirge'],
  ['massifcentral', 'Massif Central', 'Masivul Central', 4, 'Massif Central'],
  ['australianalps', 'Australian Alps', 'Alpii Australieni', 4, 'Australian Alps'],
  ['stanovoy', 'Stanovoy Range', 'Munții Stanovoi', 5, 'STANOVOY RANGE'],
  ['qinling', 'Qinling', 'Munții Qinling', 5, 'Qinling Mountains'],
  ['khingan', 'Greater Khingan', 'Marele Hingan', 5, 'GREATER KHINGAN RANGE'],
  ['cherskiy', 'Chersky Range', 'Munții Cerski', 5, 'CHERSKIY RANGE'],
  ['sikhotealin', 'Sikhote-Alin', 'Munții Sihote-Alin', 5, 'SIKHOTE-ALIN’ RANGE'],
  ['annamite', 'Annamite Range', 'Munții Annamiți', 5, 'CHAÎNE ANNAMITIQUE'],
  ['easternghats', 'Eastern Ghats', 'Ghații de Est', 5, 'EASTERN GHATS'],
  ['antiatlas', 'Anti-Atlas', 'Anti-Atlas', 5, 'Anti Atlas'],
  ['kopetdag', 'Kopet Dag', 'Munții Kopet Dag', 5, 'Kopet Dag Mts .'],
  ['sierramorena', 'Sierra Morena', 'Sierra Morena', 5, 'Sierra Morena'],
  ['blueridge', 'Blue Ridge', 'Munții Blue Ridge', 5, 'Blue Ridge'],
  ['blackhills', 'Black Hills', 'Dealurile Negre', 5, 'Black Hills'],
  ['newguinea', 'New Guinea Highlands', 'Munții Noii Guinee', 5, 'NEW GUINEA HIGHLANDS'],
  ['guiana', 'Guiana Highlands', 'Podișul Guyanelor', 5, 'GUIANA HIGHLANDS'],
  ['arakan', 'Arakan Mountains', 'Munții Arakan', 5, 'Arakan Yoma'],
  ['easternsayan', 'Eastern Sayan', 'Munții Saian', 5, 'EASTERN SAYAN MTS.'],
]

// Peaks: [id, en, ro, tier, Natural Earth name, (region filter)] or a
// hand-placed [id, en, ro, tier, null, null, lon, lat, metres].
export const PEAKS = [
  ['everest', 'Mount Everest', 'Everest', 1, 'Mount Everest'],
  ['montblanc', 'Mont Blanc', 'Mont Blanc', 1, 'Mont Blanc'],
  ['kilimanjaro', 'Kilimanjaro', 'Kilimanjaro', 1, 'Mount Kilimanjaro'],
  ['fuji', 'Mount Fuji', 'Muntele Fuji', 1, 'Fuji', 'Asia'],
  ['moldoveanu', 'Moldoveanu', 'Vârful Moldoveanu', 1, 'Moldoveanu'],
  ['vesuvius', 'Vesuvius', 'Vezuviu', 1, 'Vesuvio'],
  ['k2', 'K2', 'K2', 2, 'K2'],
  ['elbrus', 'Elbrus', 'Elbrus', 2, 'Gora Elbrus'],
  ['aconcagua', 'Aconcagua', 'Aconcagua', 2, 'Cerro Aconcagua'],
  ['denali', 'Denali', 'Denali', 2, 'Denali'],
  ['matterhorn', 'Matterhorn', 'Matterhorn', 2, 'Matterhorn'],
  ['etna', 'Etna', 'Etna', 2, 'Monte Etna'],
  ['olympus', 'Mount Olympus', 'Muntele Olimp', 2, 'Mount Olympus', 'Europe'],
  ['teide', 'Teide', 'Teide', 2, 'Pico del Teide'],
  ['kanchenjunga', 'Kangchenjunga', 'Kangchenjunga', 3, 'Kanchenjunga'],
  ['annapurna', 'Annapurna', 'Annapurna', 3, null, null, 83.820, 28.596, 8091],
  ['kenya', 'Mount Kenya', 'Muntele Kenya', 3, 'Mount Kenya'],
  ['ararat', 'Mount Ararat', 'Muntele Ararat', 3, 'Mount Ararat'],
  ['maunakea', 'Mauna Kea', 'Mauna Kea', 3, 'Mauna Kea'],
  ['kosciuszko', 'Mount Kosciuszko', 'Muntele Kosciuszko', 3, 'Mount Kosciuszko'],
  ['zugspitze', 'Zugspitze', 'Zugspitze', 3, 'Zugspitze'],
  ['hoverla', 'Hoverla', 'Hoverla', 3, null, null, 24.500, 48.160, 2061],
  ['grossglockner', 'Grossglockner', 'Grossglockner', 3, 'Grossglockner'],
  ['aoraki', 'Aoraki / Mount Cook', 'Muntele Cook', 3, 'Aoraki (Mount Cook)'],
  ['whitney', 'Mount Whitney', 'Muntele Whitney', 3, 'Mount Whitney'],
  ['popocatepetl', 'Popocatépetl', 'Popocatépetl', 3, 'Volcán Popocatépetl'],
  ['rainier', 'Mount Rainier', 'Muntele Rainier', 3, 'Mount Rainier'],
  ['bennevis', 'Ben Nevis', 'Ben Nevis', 3, 'Ben Nevis'],
  ['sthelens', 'Mount St. Helens', 'Muntele St. Helens', 3, null, null, -122.195, 46.191, 2549],
  ['tablemountain', 'Table Mountain', 'Muntele Masei', 3, null, null, 18.403, -33.957, 1085],
  ['puncakjaya', 'Puncak Jaya', 'Puncak Jaya', 4, 'Puncak Jaya'],
  ['chimborazo', 'Chimborazo', 'Chimborazo', 4, 'Chimborazo'],
  ['damavand', 'Mount Damavand', 'Muntele Damavand', 4, 'Mount Damavand'],
  ['orizaba', 'Pico de Orizaba', 'Pico de Orizaba', 4, 'Pico de Orizaba'],
  ['triglav', 'Triglav', 'Triglav', 4, 'Triglav'],
  ['musala', 'Musala', 'Musala', 4, 'Musala'],
  ['gerlach', 'Gerlachovský štít', 'Vârful Gerlach', 4, 'Gerlach'],
  ['mulhacen', 'Mulhacén', 'Mulhacén', 4, 'Mulhacén'],
  ['aneto', 'Aneto', 'Aneto', 4, 'Pico de Aneto'],
  ['toubkal', 'Toubkal', 'Toubkal', 4, 'Jebel Toubkal'],
  ['klyuchevskaya', 'Klyuchevskaya Sopka', 'Kliucevskaia Sopka', 4, 'Klyuchevskaya Sopka'],
  ['kinabalu', 'Mount Kinabalu', 'Muntele Kinabalu', 4, 'Gunung Kinabalu'],
  ['logan', 'Mount Logan', 'Muntele Logan', 4, 'Mount Logan'],
  ['kailash', 'Mount Kailash', 'Muntele Kailash', 4, 'Kailash'],
  ['huascaran', 'Huascarán', 'Huascarán', 4, 'Nevado Huascarán'],
  ['ojosdelsalado', 'Ojos del Salado', 'Ojos del Salado', 4, 'Nevado Ojos del Salado'],
  ['yushan', 'Yushan', 'Yushan', 4, 'Yu Shan'],
  ['cameroon', 'Mount Cameroon', 'Muntele Camerun', 4, 'Mont Cameroun'],
  ['duarte', 'Pico Duarte', 'Pico Duarte', 4, 'Pico Duarte'],
  ['dhaulagiri', 'Dhaulagiri', 'Dhaulagiri', 5, 'Dhaulagiri'],
  ['nangaparbat', 'Nanga Parbat', 'Nanga Parbat', 5, 'Nanga Parbat'],
  ['elgon', 'Mount Elgon', 'Muntele Elgon', 5, 'Mount Elgon'],
  ['rasdashen', 'Ras Dashen', 'Ras Dashen', 5, 'Ras Dejen'],
  ['stanley', 'Mount Stanley', 'Muntele Stanley', 5, 'Mount Stanley'],
  ['wilhelm', 'Mount Wilhelm', 'Muntele Wilhelm', 5, 'Mount Wilhelm'],
  ['grandteton', 'Grand Teton', 'Grand Teton', 5, 'Grand Teton'],
  ['belukha', 'Belukha', 'Beluha', 5, 'Belukha'],
  ['somoni', 'Ismoil Somoni Peak', 'Vârful Ismoil Somoni', 5, 'Pik Imeni Ismail Samani'],
  ['jengish', 'Jengish Chokusu', 'Vârful Pobeda', 5, 'Pik Pobeda'],
  ['shasta', 'Mount Shasta', 'Muntele Shasta', 5, 'Mount Shasta'],
  ['robson', 'Mount Robson', 'Muntele Robson', 5, 'Mount Robson'],
  ['monterosa', 'Monte Rosa', 'Monte Rosa', 5, 'Monte Rosa'],
  ['gongga', 'Gongga Shan', 'Gongga Shan', 5, 'Gongga Shan'],
]

// ---------------------------------------------------------------- waters
//
// [id, en, ro, tier, source, Natural Earth name(s)]. source is 'marine'
// (seas, gulfs, straits, oceans) or 'lake'.

export const WATERS = [
  ['blacksea', 'Black Sea', 'Marea Neagră', 1, 'marine', ['Black Sea']],
  ['mediterranean', 'Mediterranean Sea', 'Marea Mediterană', 1, 'marine', ['Mediterranean Sea']],
  ['atlantic', 'Atlantic Ocean', 'Oceanul Atlantic', 1, 'marine', ['North Atlantic Ocean', 'South Atlantic Ocean']],
  ['pacific', 'Pacific Ocean', 'Oceanul Pacific', 1, 'marine', ['North Pacific Ocean', 'South Pacific Ocean']],
  ['indian', 'Indian Ocean', 'Oceanul Indian', 1, 'marine', ['INDIAN OCEAN']],
  ['arctic', 'Arctic Ocean', 'Oceanul Arctic', 1, 'marine', ['Arctic Ocean']],
  ['caspian', 'Caspian Sea', 'Marea Caspică', 1, 'marine', ['Caspian Sea']],
  ['redsea', 'Red Sea', 'Marea Roșie', 1, 'marine', ['Red Sea']],
  ['caribbean', 'Caribbean Sea', 'Marea Caraibilor', 1, 'marine', ['Caribbean Sea']],
  ['baltic', 'Baltic Sea', 'Marea Baltică', 2, 'marine', ['Baltic Sea']],
  ['northsea', 'North Sea', 'Marea Nordului', 2, 'marine', ['North Sea']],
  ['gulfmexico', 'Gulf of Mexico', 'Golful Mexic', 2, 'marine', ['Gulf of Mexico']],
  ['persiangulf', 'Persian Gulf', 'Golful Persic', 2, 'marine', ['Persian Gulf']],
  ['adriatic', 'Adriatic Sea', 'Marea Adriatică', 2, 'marine', ['Adriatic Sea']],
  ['aegean', 'Aegean Sea', 'Marea Egee', 2, 'marine', ['Aegean Sea']],
  ['hudsonbay', 'Hudson Bay', 'Golful Hudson', 2, 'marine', ['Hudson Bay']],
  ['englishchannel', 'English Channel', 'Canalul Mânecii', 2, 'marine', ['English Channel']],
  ['arabiansea', 'Arabian Sea', 'Marea Arabiei', 2, 'marine', ['Arabian Sea']],
  ['bengal', 'Bay of Bengal', 'Golful Bengal', 2, 'marine', ['Bay of Bengal']],
  ['southchinasea', 'South China Sea', 'Marea Chinei de Sud', 2, 'marine', ['South China Sea']],
  ['seaofjapan', 'Sea of Japan', 'Marea Japoniei', 2, 'marine', ['Sea of Japan']],
  ['baikal', 'Lake Baikal', 'Lacul Baikal', 2, 'lake', ['Lake Baikal']],
  ['victoria', 'Lake Victoria', 'Lacul Victoria', 2, 'lake', ['Lake Victoria']],
  ['superior', 'Lake Superior', 'Lacul Superior', 2, 'lake', ['Lake Superior']],
  ['titicaca', 'Lake Titicaca', 'Lacul Titicaca', 2, 'lake', ['Lago Titicaca']],
  ['deadsea', 'Dead Sea', 'Marea Moartă', 2, 'lake', ['Dead Sea']],
  ['ionian', 'Ionian Sea', 'Marea Ionică', 3, 'marine', ['Ionian Sea']],
  ['tyrrhenian', 'Tyrrhenian Sea', 'Marea Tireniană', 3, 'marine', ['Tyrrhenian Sea']],
  ['norwegian', 'Norwegian Sea', 'Marea Norvegiei', 3, 'marine', ['Norwegian Sea']],
  ['barents', 'Barents Sea', 'Marea Barents', 3, 'marine', ['Barents Sea']],
  ['bering', 'Bering Sea', 'Marea Bering', 3, 'marine', ['Bering Sea']],
  ['irishsea', 'Irish Sea', 'Marea Irlandei', 3, 'marine', ['Irish Sea']],
  ['bothnia', 'Gulf of Bothnia', 'Golful Botnic', 3, 'marine', ['Gulf of Bothnia']],
  ['finland', 'Gulf of Finland', 'Golful Finic', 3, 'marine', ['Gulf of Finland']],
  ['whitesea', 'White Sea', 'Marea Albă', 3, 'marine', ['White Sea']],
  ['okhotsk', 'Sea of Okhotsk', 'Marea Ohoțk', 3, 'marine', ['Sea of Okhotsk']],
  ['yellowsea', 'Yellow Sea', 'Marea Galbenă', 3, 'marine', ['Yellow Sea']],
  ['eastchinasea', 'East China Sea', 'Marea Chinei de Est', 3, 'marine', ['East China Sea']],
  ['coralsea', 'Coral Sea', 'Marea Coralilor', 3, 'marine', ['Coral Sea']],
  ['tasman', 'Tasman Sea', 'Marea Tasmaniei', 3, 'marine', ['Tasman Sea']],
  ['aden', 'Gulf of Aden', 'Golful Aden', 3, 'marine', ['Gulf of Aden']],
  ['biscay', 'Bay of Biscay', 'Golful Biscaya', 3, 'marine', ['Bay of Biscay']],
  ['guinea', 'Gulf of Guinea', 'Golful Guineei', 3, 'marine', ['Gulf of Guinea']],
  ['mozambique', 'Mozambique Channel', 'Canalul Mozambic', 3, 'marine', ['Mozambique Channel']],
  ['azov', 'Sea of Azov', 'Marea Azov', 3, 'marine', ['Sea of Azov']],
  ['marmara', 'Sea of Marmara', 'Marea Marmara', 3, 'marine', ['Sea of Marmara']],
  ['bosporus', 'Bosporus', 'Bosfor', 3, 'marine', ['Bosporus']],
  ['gulfalaska', 'Gulf of Alaska', 'Golful Alaska', 3, 'marine', ['Gulf of Alaska']],
  ['gulfcalifornia', 'Gulf of California', 'Golful California', 3, 'marine', ['Golfo de California']],
  ['southern', 'Southern Ocean', 'Oceanul de Sud', 3, 'marine', ['SOUTHERN OCEAN']],
  ['michigan', 'Lake Michigan', 'Lacul Michigan', 3, 'lake', ['Lake Michigan']],
  ['huron', 'Lake Huron', 'Lacul Huron', 3, 'lake', ['Lake Huron']],
  ['erie', 'Lake Erie', 'Lacul Erie', 3, 'lake', ['Lake Erie']],
  ['ontario', 'Lake Ontario', 'Lacul Ontario', 3, 'lake', ['Lake Ontario']],
  ['tanganyika', 'Lake Tanganyika', 'Lacul Tanganyika', 3, 'lake', ['Lake Tanganyika']],
  ['malawi', 'Lake Malawi', 'Lacul Malawi', 3, 'lake', ['Lake Malawi']],
  ['chad', 'Lake Chad', 'Lacul Ciad', 3, 'lake', ['Lake Chad']],
  ['ladoga', 'Lake Ladoga', 'Lacul Ladoga', 3, 'lake', ['Lake Ladoga']],
  ['aral', 'Aral Sea', 'Marea Aral', 3, 'lake', ['North Aral Sea', 'South Aral Sea']],
  ['greatsalt', 'Great Salt Lake', 'Marele Lac Sărat', 3, 'lake', ['Great Salt Lake']],
  ['geneva', 'Lake Geneva', 'Lacul Geneva', 3, 'lake', ['Lake Geneva']],
  ['balaton', 'Lake Balaton', 'Lacul Balaton', 3, 'lake', ['Lake Balaton']],
  ['lochness', 'Loch Ness', 'Loch Ness', 4, 'lake', ['Loch Ness']],
  ['kara', 'Kara Sea', 'Marea Kara', 4, 'marine', ['Kara Sea']],
  ['laptev', 'Laptev Sea', 'Marea Laptev', 4, 'marine', ['Laptev Sea']],
  ['eastsiberian', 'East Siberian Sea', 'Marea Siberiei de Est', 4, 'marine', ['East Siberian Sea']],
  ['chukchi', 'Chukchi Sea', 'Marea Ciukotkăi', 4, 'marine', ['Chukchi Sea']],
  ['beaufort', 'Beaufort Sea', 'Marea Beaufort', 4, 'marine', ['Beaufort Sea']],
  ['greenlandsea', 'Greenland Sea', 'Marea Groenlandei', 4, 'marine', ['Greenland Sea']],
  ['labrador', 'Labrador Sea', 'Marea Labrador', 4, 'marine', ['Labrador Sea']],
  ['baffin', 'Baffin Bay', 'Golful Baffin', 4, 'marine', ['Baffin Bay']],
  ['philippine', 'Philippine Sea', 'Marea Filipinelor', 4, 'marine', ['Philippine Sea']],
  ['java', 'Java Sea', 'Marea Java', 4, 'marine', ['Java Sea']],
  ['andaman', 'Andaman Sea', 'Marea Andaman', 4, 'marine', ['Andaman Sea']],
  ['arafura', 'Arafura Sea', 'Marea Arafura', 4, 'marine', ['Arafura Sea']],
  ['timor', 'Timor Sea', 'Marea Timor', 4, 'marine', ['Timor Sea']],
  ['oman', 'Gulf of Oman', 'Golful Oman', 4, 'marine', ['Gulf of Oman']],
  ['thailand', 'Gulf of Thailand', 'Golful Thailandei', 4, 'marine', ['Gulf of Thailand']],
  ['bight', 'Great Australian Bight', 'Marele Golf Australian', 4, 'marine', ['Great Australian Bight']],
  ['carpentaria', 'Gulf of Carpentaria', 'Golful Carpentaria', 4, 'marine', ['Gulf of Carpentaria']],
  ['ligurian', 'Ligurian Sea', 'Marea Ligurică', 4, 'marine', ['Ligurian Sea']],
  ['balearic', 'Balearic Sea', 'Marea Baleară', 4, 'marine', ['Balearic Sea']],
  ['riga', 'Gulf of Riga', 'Golful Riga', 4, 'marine', ['Gulf of Riga']],
  ['lion', 'Gulf of Lion', 'Golful Leului', 4, 'marine', ['Golfe du Lion']],
  ['plata', 'Río de la Plata', 'Río de la Plata', 4, 'marine', ['Río de la Plata']],
  ['malacca', 'Strait of Malacca', 'Strâmtoarea Malacca', 4, 'marine', ['Strait of Malacca']],
  ['dardanelles', 'Dardanelles', 'Dardanele', 4, 'marine', ['Dardanelles']],
  ['sargasso', 'Sargasso Sea', 'Marea Sargaselor', 4, 'marine', ['Sargasso Sea']],
  ['weddell', 'Weddell Sea', 'Marea Weddell', 4, 'marine', ['Weddell Sea']],
  ['ross', 'Ross Sea', 'Marea Ross', 4, 'marine', ['Ross Sea']],
  ['maracaibo', 'Lake Maracaibo', 'Lacul Maracaibo', 4, 'marine', ['Lago de Maracaibo']],
  ['onega', 'Lake Onega', 'Lacul Onega', 4, 'lake', ['Lake Onega']],
  ['turkana', 'Lake Turkana', 'Lacul Turkana', 4, 'lake', ['Lake Turkana']],
  ['winnipeg', 'Lake Winnipeg', 'Lacul Winnipeg', 4, 'lake', ['Lake Winnipeg']],
  ['greatbear', 'Great Bear Lake', 'Marele Lac al Ursului', 4, 'lake', ['Great Bear Lake']],
  ['greatslave', 'Great Slave Lake', 'Marele Lac al Sclavilor', 4, 'lake', ['Great Slave Lake']],
  ['nicaragua', 'Lake Nicaragua', 'Lacul Nicaragua', 4, 'lake', ['Lago de Nicaragua']],
  ['constance', 'Lake Constance', 'Lacul Constanța', 4, 'lake', ['Bodensee']],
  ['van', 'Lake Van', 'Lacul Van', 4, 'lake', ['Lake Van']],
  ['nasser', 'Lake Nasser', 'Lacul Nasser', 4, 'lake', ['Lake Nasser']],
  ['balkhash', 'Lake Balkhash', 'Lacul Balhaș', 4, 'lake', ['Lake Balkhash']],
  ['celebes', 'Celebes Sea', 'Marea Celebes', 5, 'marine', ['Celebes Sea']],
  ['sulu', 'Sulu Sea', 'Marea Sulu', 5, 'marine', ['Sulu Sea']],
  ['banda', 'Banda Sea', 'Marea Banda', 5, 'marine', ['Banda Sea']],
  ['bismarck', 'Bismarck Sea', 'Marea Bismarck', 5, 'marine', ['Bismarck Sea']],
  ['laccadive', 'Laccadive Sea', 'Marea Laccadive', 5, 'marine', ['Laccadive Sea']],
  ['tonkin', 'Gulf of Tonkin', 'Golful Tonkin', 5, 'marine', ['Gulf of Tonkin']],
  ['bohai', 'Bohai Sea', 'Marea Bohai', 5, 'marine', ['Bo Hai']],
  ['taiwanstrait', 'Taiwan Strait', 'Strâmtoarea Taiwan', 5, 'marine', ['Taiwan Strait']],
  ['davis', 'Davis Strait', 'Strâmtoarea Davis', 5, 'marine', ['Davis Strait']],
  ['bristolbay', 'Bristol Bay', 'Golful Bristol', 5, 'marine', ['Bristol Bay']],
  ['chesapeake', 'Chesapeake Bay', 'Golful Chesapeake', 5, 'marine', ['Chesapeake Bay']],
  ['fundy', 'Bay of Fundy', 'Golful Fundy', 5, 'marine', ['Bay of Fundy']],
  ['stlawrence', 'Gulf of St. Lawrence', 'Golful Sfântul Laurențiu', 5, 'marine', ['Gulf of Saint Lawrence']],
  ['tana', 'Lake Tana', 'Lacul Tana', 5, 'lake', ['Lake Tana']],
  ['kivu', 'Lake Kivu', 'Lacul Kivu', 5, 'lake', ['Lake Kivu']],
  ['issykkul', 'Issyk-Kul', 'Lacul Issîk-Kul', 5, 'lake', ['Issyk-Kul']],
  ['urmia', 'Lake Urmia', 'Lacul Urmia', 5, 'lake', ['Lake Urmia']],
  ['tonlesap', 'Tonlé Sap', 'Tonlé Sap', 5, 'lake', ['Tonlé Sap']],
  ['qinghai', 'Qinghai Lake', 'Lacul Qinghai', 5, 'lake', ['Qinghai Hu']],
  ['kariba', 'Lake Kariba', 'Lacul Kariba', 5, 'lake', ['Lake Kariba']],
  ['volta', 'Lake Volta', 'Lacul Volta', 5, 'lake', ['Lake Volta']],
  ['eyre', 'Lake Eyre', 'Lacul Eyre', 5, 'lake', ['Lake Eyre North', 'Lake Eyre South']],
  ['vanern', 'Lake Vänern', 'Lacul Vänern', 5, 'lake', ['Vänern']],
  ['saimaa', 'Lake Saimaa', 'Lacul Saimaa', 5, 'lake', ['Lake Saimaa']],
  ['loughneagh', 'Lough Neagh', 'Lough Neagh', 5, 'lake', ['Lough Neagh']],
  ['como', 'Lake Como', 'Lacul Como', 5, 'lake', ['Lago di Como']],
  ['garda', 'Lake Garda', 'Lacul Garda', 5, 'lake', ['Lago di Garda']],
  ['sevan', 'Lake Sevan', 'Lacul Sevan', 5, 'lake', ['Lake Sevan']],
  ['peipus', 'Lake Peipus', 'Lacul Peipus', 5, 'lake', ['Lake Peipus']],
]
