#!/usr/bin/env node
// Writes sw.js: the offline precache for everything the game ships.
// Both generators call this; it can also be run on its own after editing
// any hand-written file: node tools/build-sw.mjs
//
// The cache name hashes file *contents*, not just the file list - otherwise
// an edited app.js keeps the old cache name and an installed tablet would
// serve the stale copy forever.

import { readdir, readFile, writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

async function walk(dir, root, out) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) await walk(full, root, out)
    else out.push(path.relative(root, full).split(path.sep).join('/'))
  }
  return out
}

export async function writeServiceWorker(root) {
  const files = ['index.html', 'manifest.webmanifest']
  files.push(...(await walk(path.join(root, 'css'), root, [])).filter((f) => f.endsWith('.css')))
  files.push(...(await walk(path.join(root, 'js'), root, [])).filter((f) => f.endsWith('.js')))
  files.push(...(await walk(path.join(root, 'assets'), root, [])).filter((f) => f.endsWith('.png')))
  files.sort()

  const hash = createHash('sha1')
  for (const f of files) hash.update(f).update(await readFile(path.join(root, f)))
  const version = hash.digest('hex').slice(0, 8)
  const assets = ['./'].concat(files.map((f) => './' + f))

  await writeFile(path.join(root, 'sw.js'), `// GENERATED by tools/build-sw.mjs - do not edit by hand.
var CACHE = 'steaguri-${version}';
var ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(CACHE).then(function (c) {
    // Straight from the network: the HTTP cache (GitHub Pages lets browsers
    // keep files for 10 minutes) could hand back the previous version.
    // Individual misses must not fail the whole install.
    return Promise.all(ASSETS.map(function (url) {
      return fetch(new Request(url, { cache: 'reload' })).then(function (res) {
        if (res.ok) return c.put(url, res);
      }).catch(function () {});
    }));
  }).then(function () { return self.skipWaiting(); }));
});

// Asks an open page whether it will move to the new version by itself. Pages
// from before this version never answer.
function handlesUpdate(client) {
  return new Promise(function (resolve) {
    var ch = new MessageChannel();
    ch.port1.onmessage = function (e) { resolve(!!(e.data && e.data.handled)); };
    setTimeout(function () { resolve(false); }, 1000);
    client.postMessage({ type: 'updated' }, [ch.port2]);
  });
}

// This replaced an older version: every open page moves onto it, so nobody
// has to force a refresh. A page in the middle of a game says so and reloads
// itself once the game is over; a page too old to answer is reloaded here.
function moveOpenPages() {
  return self.clients.matchAll({ type: 'window' }).then(function (list) {
    return Promise.all(list.map(function (client) {
      return handlesUpdate(client).then(function (handled) {
        if (!handled && client.navigate) return client.navigate(client.url).catch(function () {});
      });
    }));
  });
}

self.addEventListener('activate', function (e) {
  var replaced = false;
  var ready = caches.keys().then(function (keys) {
    var old = keys.filter(function (k) { return k !== CACHE; });
    replaced = old.length > 0;
    return Promise.all(old.map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); });
  e.waitUntil(ready);
  // Only once activation is over: until then the browser holds every page
  // request, so reloading a page from inside it would wait forever.
  ready.then(function () { if (replaced) setTimeout(moveOpenPages, 0); });
});

self.addEventListener('fetch', function (e) {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.match(e.request).then(function (hit) {
    return hit || fetch(e.request).then(function (res) {
      if (res && res.status === 200 && res.type === 'basic') {
        var copy = res.clone();
        caches.open(CACHE).then(function (c) { c.put(e.request, copy); });
      }
      return res;
    }).catch(function () { return caches.match('./index.html'); });
  }));
});
`)
  console.log(`wrote sw.js (${assets.length} assets, cache steaguri-${version})`)
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  writeServiceWorker(path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..'))
    .catch((err) => { console.error(err); process.exit(1) })
}
